### ISSUE TITLE
Не реализованна вторая часть задания

### ISSUE THREAD

**Issue by couchemar** [MarinaaaniraM/tornado_tcpserver#1]
>  Предоставлять веб-интерфейс состоящий из одной страницы, на которой
>  можно увидеть присылаемые источниками сообщения в формате:
>  "[SourceName] KEY | Value". Каждое такое сообщение должно появляться
>  сразу после того, как будет полностью принято. Также на странице
>  должен присутствовать список подключенных в данный момент источников.

**Comment by marinaaaniram** [comment]
Добавила веб-интерфейс. 
Есть вопрос по заданию. Если одновременно подключено несколько источников, то как понимать, от какого именно пришло сообщение 'End'?

**Comment by ILJICH** [comment]
Так каждое подключение подключение обрабатывается отдельно же.
Довольно странно слышать такой вопрос если учесть что код написан в целом правильно.

**Comment by marinaaaniram** [comment]
Добавила отображение списка поключенных устройств.
